if (!requireNamespace("BiocManager", quietly = TRUE))
install.packages("BiocManager")
BiocManager::install("plotgardener")
BiocManager::install("plotgardenerData")
pdf("/Users/rishabhvemuri/Downloads/pgUI/resources/temp.pdf", width = 5, height = 5)
library(plotgardener)
library(plotgardenerData)
data("IMR90_HiC_10kb")
pageCreate(width = 3, height = 3, )
dev.off()
